# Permalinks
permalink:

# Setup
title:               Scuttle
tagline:             When all else fails
url:                 http://scut.tl
paginate:            1
baseurl:             "http://tsagadai.github.io/scut.tl/"

# Assets
#
# We specify the directory for Jekyll so we can use @imports.
sass:
  sass_dir:          _sass
  style:            :compressed

# About/contact
author:
  name:              Chris Curran
  url:               https://twitter.com/Tsagadai
  email:             chris@scut.tl

# Custom vars
version:             2.0.0
github:
  repo:              https://github.com/poole/poole

# Gems
gems:
  - jekyll-paginate
  - jekyll-gist
  - github-pages
